name: Build DXVK Remix

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Add Graphics Drivers PPA
      run: |
        sudo add-apt-repository -y ppa:graphics-drivers/ppa
        sudo apt-get update

    - name: Install Dependencies
      run: |
        sudo apt-get install -y build-essential git python3 python3-pip ninja-build meson
        sudo apt-get install -y vulkan-utils

    - name: Clone Repository
      run: |
        git clone --recursive https://github.com/NVIDIAGameWorks/dxvk-remix.git
        cd dxvk-remix
        git submodule update --init --recursive

    - name: Build dxvk_rt Project
      run: |
        cd dxvk-remix
        meson --buildtype=release _Comp64Release
        ninja -C _Comp64Release

    - name: Create Zip Archive
      run: |
        cd dxvk-remix
        zip -r dxvk-remix.zip *

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dxvk-remix
        path: dxvk-remix.zip
