name: Build DXVK Remix

on: [workflow_dispatch]

jobs:
  build-dxvk_rt:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        choco install python --version=3.9 -y
        choco install visualstudio2019community --package-parameters "--includeRecommended --includeOptional --passive" -y
        choco install vulkan-sdk --version=1.3.211.0 -y
        choco install meson --version=0.61.4 -y

    - name: Build dxvk_rt
      shell: powershell
      run: |
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process
        .\build_dxvk_all_ninja.ps1

